[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/livestream"
  to = "https://youtu.be/jL5LGzdOoBk"
  status = 301

[[redirects]]
  from = "/welcome"
  to = "https://help.osoc.be/osoc21"
  status = 301

[[redirects]]
  from = "/companies"
  to = "/partners"
  status = 301

[[redirects]]
  from = "/2019"
  to = "/editions#2019"
  status = 301

[[redirects]]
  from = "/2020"
  to = "/editions#2020"
  status = 301

[[redirects]]
  from = "/2021"
  to = "/editions#2021"
  status = 301

[[redirects]]
  from = "/2022"
  to = "/editions#2022"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/editions#2022"
  status = 302
